name: ucg CI
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  script-tci:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to build and test your code on the runner."
      - name: Display tool versions
        run: |
          gcc --version
          clang --version
      - name: autoreconf -i
        run: autoreconf -i
      - name: Make build directory
        run: |
          mkdir build
          cd build
      - name: Configure
        run: |
          echo "CFG_CC=$CFG_CC CFG_CXX=$CFG_CXX"
          ../configure CC="$CFG_CC" CXX="$CFG_CXX"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
